google.client_id=404365163109-ff3qpodugi6lab4vt3upl5m7590l7sj4.apps.googleusercontent.com
google.client_secret=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
google.redirect_uris=http://localhost:3000/
google.project_id=djangorest-457112
google.auth_uri=https://accounts.google.com/o/oauth2/auth
google.token_uri=https://oauth2.googleapis.com/token
google.auth_provider_x509_cert_url=https://www.googleapis.com/oauth2/v1/certs

