momo.partnerCode=MOMO
momo.accessKey=F8BBA842ECF85
momo.secretKey=K951B6PE1waDMi640xX08PD3vg6EkVlz
momo.endpoint=https://test-payment.momo.vn/v2/gateway/api/create
momo.redirectUrl=https://closely-tough-glowworm.ngrok-free.app/TicketSale/api/secure/payment/callback/momo/redirect
momo.ipnUrl=https://closely-tough-glowworm.ngrok-free.app/TicketSale/api/secure/payment/callback/momo/ipn

vnpay.tmnCode=YQ25WFOQ
vnpay.hashSecret=MRCBBDHX1OLTX9M489SMY6AKVQT4BN06
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.returnUrl=https://closely-tough-glowworm.ngrok-free.app/TicketSale/api/secure/payment/callback/vnpay

payment.currency=VND
payment.locale=vn
frontend.baseUrl=http://localhost:3000
